name: Cypress E2E Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run